### ISSUE TITLE
guide for wpa3 would be great

### ISSUE THREAD

**Issue by ABerTSC** [morrownr/8812au-20210629#11]
hi for the linux beginners a guide for the wpa3 would be super!

**Comment by morrownr** [comment]
Hi @ABerTSC 

Are you willing to test it?

**Comment by morrownr** [comment]
I have completed a guide. I will post it after I have tested it a few more times.

It will come with the following disclaimer:

Disclaimer: This guide attempts to help you install software that has not been
released. This may break your system. If it does break your system, you own it.

**Comment by ABerTSC** [comment]
I would test it if you like yes.

**Comment by morrownr** [comment]
/home/morrow/AppDev/wpa-supplicant/update_wpa_supplicant

**Comment by morrownr** [comment]
[update_wpa_supplicant.txt](https://github.com/morrownr/8812au-20210629/files/7567872/update_wpa_supplicant.txt)

Please report as you are able.

**Comment by usama7628674** [comment]
I can test this.

**Comment by usama7628674** [comment]
old wpa_supplicant
![image](https://user-images.githubusercontent.com/29252277/142715791-91adc95d-5297-4591-8943-c75fc92eb97f.png)

New wpa_supplicant
![image](https://user-images.githubusercontent.com/29252277/142715808-006c8835-fdba-4943-bed2-f86f7437bcf6.png)

**Comment by usama7628674** [comment]
Now to spawn wpa3-SAE with hostapd and connect with latest version of wpa_supplicant

**Comment by usama7628674** [comment]
I have a question. I only have only `rtl8812au` based adapter. Should I spawn AP with `rtl8812au` using hostapd and connect with `AWUS036ACHM` (supports WPA3-SAE) using latest wpa_supplicant or vice versa or Should I need to `rtl8812au` adapters to test WPA3-SAE?

**Comment by usama7628674** [comment]
Okay, so I have used `Atheros ar9565` for hostapd and used `rtl8812au` for wpa_supplicant to connect to AP and I can conform SAE is supported.
![image](https://user-images.githubusercontent.com/29252277/142717357-34647ff6-3ae4-4d06-b3d5-866caf9b0c22.png)

**Comment by usama7628674** [comment]
hostpad.conf 
```
interface=wlan0
ssid=WPA3-Network

hw_mode=g
channel=1

wpa=2
wpa_passphrase=abcdefgh
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
ieee80211w=2
```

wpa_supplicant.conf
```
network={
    ssid="WPA3-Network"
    psk="abcdefgh"
    key_mgmt=SAE
    ieee80211w=2
}
```

**Comment by morrownr** [comment]
No, you do not need 2 8812au adapters to test if WPA3 works. How about testing it first in client mode. In this case, you simply need an access point that supports WPA3. That access point can be from a regular wifi router or from an access point that you made. I can tell you that your ALFA ACHM and a RasPi support WPA3 because I have tested it many times and no wpa_supplicant upgrade us required for adapters that use in-kernel drivers like the ACHM. If you use a RasPi with your ACHM as an AP for testing WAP3, here are the vital settings to activate WPA3 for hostapd.conf:

auth_algs=3
wpa=2
rsn_pairwise=CCMP
wpa_key_mgmt=SAE
ieee80211w=2

**Comment by morrownr** [comment]
> Okay, so I have used `Atheros ar9565` for hostapd and `rtl8812au` for wpa_supplicant to connect to AP and I can confirm SAE is supported. ![image](https://user-images.githubusercontent.com/29252277/142717357-34647ff6-3ae4-4d06-b3d5-866caf9b0c22.png)

That is a very positive result. I appreciate you for testing. I am going to edit the guide now to make it more simple. Once it is complete, I will post it here and we need to come up with a plan for wider testing before adding information to the README. Thoughts?

**Comment by usama7628674** [comment]
When you post guide to enable wpa3 support, I'll retest based on a simple guide you post here.

**Comment by morrownr** [comment]
> When you post guide to enable wpa3 support, I'll retest based on a simple guide you post here.

New guide is posted. See #17

**Comment by ABerTSC** [comment]
hi i cant find #17 why its is gone?
