### ISSUE TITLE
having partially issues using ALFA AWUS036ACH on rpi5 running bookworm

### ISSUE THREAD

**Issue by bungh0l10** [morrownr/8812au-20210629#112]
Hi,

I've setup this driver on a rpi5 running headless RaspbianOS bookworm lite 64bit for testing.
The driver install went fine without any issue and the ALFA AWUS036ACH WiFi USB Adapter acts as an AP configured though networkmanager.

So far so good, all devices can connect and browse using the AP but my laptop (TravelMate Spin B311RN-31) running Arch Linux acts super slow after being connected.
For example having a termnial SSH session open (on the laptop connected to the rpi) executing commands like apt-get upgrade where you usually can see live what's going on, nothing visually noticeable happens. At one point later you can see the summary of what happened XD. Opening a website can take up to 30 seconds. 

This does not happen while using rpi5 built in wifi adapter or attaching ALFA AWUS036ACHM WiFi USB Adapter.
I also haven't had any trouble with my main device rpi4 running bullseye. 

I really don't know what details to report, as I don't see any obvious errors within dmesg /journalctl.
Maybe you have an idea? If you need more information please let me know, thank you :)

my laptops wifi card:
<details>
<pre><code>
00:0c.0 Network controller: Intel Corporation Gemini Lake PCH CNVi WiFi (rev 06)
	Subsystem: Intel Corporation Wireless-AC 9560
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi
</code></pre>
</details>

cheers

**Comment by morrownr** [comment]
Hi @bungh0l10 

> ...Adapter acts as an AP configured though networkmanager.

I have an AP mode guide here at this site. The Main Menu of this site is located:

https://github.com/morrownr/USB-WiFi

Menu item 9 shows the AP guide, My guide uses hostapd and systemd-networkd. NetworkManager is deactivated. Unless things have changed since the last time I experimented with NetworkManager and AP mode, NM does not allow for getting the best performance in AP mode. The setup in my guide will allow you to get all of the performance that is available plus it is VERY stable. Take a look at my guide and if you have questions, you can post questions in the Issues located on Main Menu.

@morrownr

**Comment by bungh0l10** [comment]
Hi @morrownr 

thanks for the hint. I wanted to give nm a try and thought reporting might be a good thing but you answer was very clear. I switched to systemd-networkd / hostapd and it's a diference like night and day :) .

Thanks again , cheers

**Comment by bungh0l10** [comment]
Thanks @morrownr appreciate your help, all input welcome.

My current hostapd.conf is very basic:

country_code=DE
bridge=br0
interface=wlan0
ssid=
hw_mode=g
channel=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
ieee80211n=1
ieee80211d=1
wmm_enabled=1
wpa=2
wpa_passphrase=
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

The AP itself is setup in my garden shed to spread WiFi for my old but gold squeezebox music streamers which are b/g/n devices.

I'm not sure if I missed it but would it be possible to configure a dual WiFi 2.4/5 GHz AP where I can connect my music streamers to 2.4 and my mobiles / laptops to 5 GHz?

Thanks again, cheers!

**Comment by morrownr** [comment]
> My current hostapd.conf is very basic:

Yes, that is very basic. It is possible to dramatically improve your performance, especially if your were using the adapter for 5 GHz. The example WiFi-5 hostapd.conf in my guide gives specific setting for the rtl8812au chipset. You can try and if you mess it up, you can post it here and I can help.

> I'm not sure if I missed it but would it be possible to configure a dual WiFi 2.4/5 GHz AP where I can connect my music streamers to 2.4 and my mobiles / laptops to 5 GHz?

Yes, my guide goes into detail about how to set things up for dual band operation.
