### ISSUE TITLE
(the problem is not in this driver) Causes network tools to hang on 6.1.66

### ISSUE THREAD

**Issue by MaxHearnden** [morrownr/8812au-20210629#113]
This causes hangs with network tools (e.g. ifconfig) when using 6.1.66, specifically when https://github.com/torvalds/linux/commit/307a6525c82a5a1bc5364711ece92c2d2487e1ad is applied.

**Comment by morrownr** [comment]
> network tools (e.g. ifconfig)

ifconfig has been depreciated for many years. Recommend you use ip and iw. They are the modern supported network tools.
