### ISSUE TITLE
(solved - this driver is for the 8812au chipset and does not support the 8811au chipset) Edimax C600

### ISSUE THREAD

**Issue by sdack** [morrownr/8812au-20210629#27]
Hello,

I have an Edimax C600 USB WiFi adapter, which does not exist yet in the device ID list:

`ID 7392:a812 Edimax Technology Co., Ltd Edimax AC600 USB`

(Only the 7392:a822 version is currently supported.)

Vendor link:
https://www.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/in/wireless_adapters_ac600_dual-band/ew-7811uac/

The device has been working well for a long time with the RTL8812AU Aircrack-NG driver (ver. 5.6.4.2). After adding the missing ID to the driver here did I notice that it was constantly randomising its MAC address, which led to the device name being randomised too (i.e. wlx_randomstuff_), making it hard to be used in scripts and hostapd.conf. The Aircrack-NG driver picks up the default hardware MAC address just fine however. I have worked around it by setting the module parameter `rtw_initmac` to a fixed address. Is there a way to let it pick up the default MAC address automatically the way the Aircrack driver does it?

**Comment by morrownr** [comment]
Hi @sdack 

You installed the wrong driver. Run the following:

$ sudo ./remove-driver.sh

Then go to:

https://github.com/morrownr/8821au-20210708

Your adapter contains a rtl8811au chipset. The driver in this repo is for the rtl8812au chipset.

I am aware that the Aircrack-NG driver contains support for both chipsets. I do not know the history of how that came about but I do know that the current Aircrack-NG driver is based on old code. You will likely be very pleased with the 8811au driver when you install it.

Regards

**Comment by sdack** [comment]
Thank you.
