### ISSUE TITLE
5GHz WIFI repeatedly asks for password never connects. Kernel v5.16|v15.5  - Ubuntu|PopOS

### ISSUE THREAD

**Issue by pygaurav** [morrownr/8812au-20210629#52]
I am using PopOS currently, I am unable to connect to 5GHz wifi, it repeatedly asks for password & never connects.

**Comment by Bartholomew42** [comment]
Hi @pygaurav , 

what channel is that wifi network on? 
What is the output of `iwlist chan` ? 
What is the output of `iw list | grep MHz`? 
What is the output of `grep [[:alnum:]] /sys/module/8812au/parameters/* | grep country` ?

(Because I myself had trouble with the country code setting, my mind is primed with the idea that you might have a similar problem. I might be completely wrong and your problem might originate from something completely different.)

Greetings!

**Comment by pygaurav** [comment]
Hi @Bartholomew42 ,

Thank you for your comment. Please find the below output for your reference.


Channel is 44
Output of `iwlist chan`:


    lo        no frequency information.
    
    enp3s0    no frequency information.
    
    wlp2s0    32 channels in total; available frequencies :
              Channel 01 : 2.412 GHz
              Channel 02 : 2.417 GHz
              Channel 03 : 2.422 GHz
              Channel 04 : 2.427 GHz
              Channel 05 : 2.432 GHz
              Channel 06 : 2.437 GHz
              Channel 07 : 2.442 GHz
              Channel 08 : 2.447 GHz
              Channel 09 : 2.452 GHz
              Channel 10 : 2.457 GHz
              Channel 11 : 2.462 GHz
              Channel 12 : 2.467 GHz
              Channel 13 : 2.472 GHz
              Channel 34 : 5.17 GHz
              Channel 36 : 5.18 GHz
              Channel 38 : 5.19 GHz
              Channel 40 : 5.2 GHz
              Channel 42 : 5.21 GHz
              Channel 44 : 5.22 GHz
              Channel 46 : 5.23 GHz
              Channel 48 : 5.24 GHz
              Channel 52 : 5.26 GHz
              Channel 56 : 5.28 GHz
              Channel 60 : 5.3 GHz
              Channel 64 : 5.32 GHz
              Channel 100 : 5.5 GHz
              Channel 104 : 5.52 GHz
              Channel 108 : 5.54 GHz
              Channel 112 : 5.56 GHz
              Channel 116 : 5.58 GHz
              Channel 120 : 5.6 GHz
              Channel 124 : 5.62 GHz
              Current Frequency:2.462 GHz (Channel 11)
    
    wlxd03745aeb6c3  32 channels in total; available frequencies :
              Channel 01 : 2.412 GHz
              Channel 02 : 2.417 GHz
              Channel 03 : 2.422 GHz
              Channel 04 : 2.427 GHz
              Channel 05 : 2.432 GHz
              Channel 06 : 2.437 GHz
              Channel 07 : 2.442 GHz
              Channel 08 : 2.447 GHz
              Channel 09 : 2.452 GHz
              Channel 10 : 2.457 GHz
              Channel 11 : 2.462 GHz
              Channel 36 : 5.18 GHz
              Channel 40 : 5.2 GHz
              Channel 44 : 5.22 GHz
              Channel 48 : 5.24 GHz
              Channel 52 : 5.26 GHz
              Channel 56 : 5.28 GHz
              Channel 60 : 5.3 GHz
              Channel 64 : 5.32 GHz
              Channel 100 : 5.5 GHz
              Channel 104 : 5.52 GHz
              Channel 108 : 5.54 GHz
              Channel 112 : 5.56 GHz
              Channel 116 : 5.58 GHz
              Channel 120 : 5.6 GHz
              Channel 124 : 5.62 GHz
              Channel 128 : 5.64 GHz
              Channel 132 : 5.66 GHz
              Channel 136 : 5.68 GHz
              Channel 140 : 5.7 GHz
              Channel 149 : 5.745 GHz
              Channel 153 : 5.765 GHz
              Current Frequency:5.22 GHz (Channel 44)

Output of ``iw list | grep MHz``

    * 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm)
			* 2472 MHz [13] (20.0 dBm)
			* 2484 MHz [14] (20.0 dBm)
			short GI (80 MHz)
			* 5075 MHz [15] (30.0 dBm)
			* 5080 MHz [16] (30.0 dBm)
			* 5085 MHz [17] (30.0 dBm)
			* 5090 MHz [18] (30.0 dBm)
			* 5100 MHz [20] (30.0 dBm)
			* 5120 MHz [24] (30.0 dBm)
			* 5140 MHz [28] (30.0 dBm)
			* 5160 MHz [32] (30.0 dBm)
			* 5180 MHz [36] (30.0 dBm)
			* 5200 MHz [40] (30.0 dBm)
			* 5220 MHz [44] (30.0 dBm)
			* 5240 MHz [48] (30.0 dBm)
			* 5260 MHz [52] (24.0 dBm)
			* 5280 MHz [56] (24.0 dBm)
			* 5300 MHz [60] (24.0 dBm)
			* 5320 MHz [64] (24.0 dBm)
			* 5340 MHz [68] (24.0 dBm)
			* 5360 MHz [72] (30.0 dBm)
			* 5380 MHz [76] (30.0 dBm)
			* 5400 MHz [80] (30.0 dBm)
			* 5420 MHz [84] (30.0 dBm)
			* 5440 MHz [88] (30.0 dBm)
			* 5460 MHz [92] (30.0 dBm)
			* 5480 MHz [96] (24.0 dBm)
			* 5500 MHz [100] (24.0 dBm)
			* 5520 MHz [104] (24.0 dBm)
			* 5540 MHz [108] (24.0 dBm)
			* 5560 MHz [112] (24.0 dBm)
			* 5580 MHz [116] (24.0 dBm)
			* 5600 MHz [120] (24.0 dBm)
			* 5620 MHz [124] (24.0 dBm)
			* 5640 MHz [128] (24.0 dBm)
			* 5660 MHz [132] (24.0 dBm)
			* 5680 MHz [136] (24.0 dBm)
			* 5700 MHz [140] (24.0 dBm)
			* 5720 MHz [144] (24.0 dBm)
			* 5745 MHz [149] (30.0 dBm)
			* 5765 MHz [153] (30.0 dBm)
			* 5785 MHz [157] (30.0 dBm)
			* 5805 MHz [161] (30.0 dBm)
			* 5825 MHz [165] (30.0 dBm)
			* 5845 MHz [169] (30.0 dBm)
			* 5865 MHz [173] (30.0 dBm)
			* 5885 MHz [177] (30.0 dBm)
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm)
			* 2472 MHz [13] (20.0 dBm)
			* 2484 MHz [14] (disabled)
			* 5170 MHz [34] (30.0 dBm)
			* 5180 MHz [36] (30.0 dBm)
			* 5190 MHz [38] (30.0 dBm)
			* 5200 MHz [40] (30.0 dBm)
			* 5210 MHz [42] (30.0 dBm)
			* 5220 MHz [44] (30.0 dBm)
			* 5230 MHz [46] (30.0 dBm)
			* 5240 MHz [48] (30.0 dBm)
			* 5260 MHz [52] (24.0 dBm)
			* 5280 MHz [56] (24.0 dBm)
			* 5300 MHz [60] (24.0 dBm)
			* 5320 MHz [64] (24.0 dBm)
			* 5500 MHz [100] (24.0 dBm)
			* 5520 MHz [104] (24.0 dBm)
			* 5540 MHz [108] (24.0 dBm)
			* 5560 MHz [112] (24.0 dBm)
			* 5580 MHz [116] (24.0 dBm)
			* 5600 MHz [120] (24.0 dBm)
			* 5620 MHz [124] (24.0 dBm)
			* 5640 MHz [128] (24.0 dBm)
			* 5660 MHz [132] (24.0 dBm)
			* 5680 MHz [136] (24.0 dBm)
			* 5700 MHz [140] (24.0 dBm)
			* 5745 MHz [149] (30.0 dBm)
			* 5765 MHz [153] (30.0 dBm)
			* 5785 MHz [157] (30.0 dBm)
			* 5805 MHz [161] (30.0 dBm)
			* 5825 MHz [165] (30.0 dBm)
			* 5920 MHz [184] (disabled)
			* 5940 MHz [188] (disabled)
			* 5960 MHz [2] (disabled)
			* 5980 MHz [6] (disabled)
			* 6000 MHz [10] (disabled)
			* 6020 MHz [14] (disabled)
			* 6040 MHz [18] (disabled)
			* 6060 MHz [22] (disabled)
			* 6080 MHz [26] (disabled)

Output of ``grep [[:alnum:]] /sys/module/8812au/parameters/* | grep rtw_c``

    /sys/module/8812au/parameters/rtw_channel:1
    /sys/module/8812au/parameters/rtw_channel_plan:255
    /sys/module/8812au/parameters/rtw_check_hw_status:0
    /sys/module/8812au/parameters/rtw_chip_version:0
    /sys/module/8812au/parameters/rtw_ch_switch_offload:0

**Comment by Bartholomew42** [comment]
Hi @pygaurav , 
it seems to me that my initial idea was probably wrong. 
I think this could be an authentication error that has little to do with the driver. 

Such errors can occur when 
a) the access point and the client are far apart and can't receive each other very well (low signal strength on any side). Moving the client nearer to the access point will help in this situation. 
b) the access point won't allow the client to log in for any reason (the access point does not like the clients MAC address, some wifi security setting is wrong, a typing error in the password). 

Can you connect to the desired network using your other wifi network adapter (wlp2s0)? 
Do you have access to the log files of the access point?
Can you test if you can connect to any other 5GHz network with your 8812au adapter?

Greetings!

**Comment by pygaurav** [comment]
Hi @Bartholomew42 ,

I was using Ubuntu 20.04 in the morning & it was working fine (as it was using the older kernel version). But when I upgraded to Ubuntu 22.04 problem start appearing (I am sure the error is because of the kernel version i.e. v5.16).

I am able to connect with my inbuilt adapter but the error is coming with the USB one.

Could you please suggest how can I change my `rtw_country_code`?

**Comment by pygaurav** [comment]
I have changed value of `rtw_country_code` it is working fine now.

**Comment by Bartholomew42** [comment]
To change it temporarily until the next loading of the driver (in most times, the next booting of Ubuntu), use `sudo modprobe -r 8812au` (this unloads the driver), the reload it using `sudo modprobe 8812au rtw_country_code=XY` whereas XY has to be the identifier for your country (BR for Brazil, CN for China, CH for Switzerland and so on: [https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements](url) ). 
You can check if the driver was loaded with the desired option with `grep [[:alnum:]] /sys/module/8812au/parameters/*|grep rtw_co`. In my case, the output is `/sys/module/8812au/parameters/rtw_country_code:DE` .
If you want to set the option permanently, use `sudo nano /etc/modprobe.d/8812au.conf` and add `rtw_country_code=XY` to the line with all the other options at the top of the config file. You can apply the change with a reboot or with `sudo modprobe -r 8812au & modprobe 8812au`.
