### ISSUE TITLE
ibss support

### ISSUE THREAD

**Issue by smydoudou** [morrownr/8812au-20210629#57]
Hi,
I'm using 2 nvidia tx2 boards for wireless module. After installing rtl8812au driver, I checked normal wifi connection is no problem. But in ad-hoc mode the boards can't communicate each other even though they are in same essid, cell, frequency... 
Is this a known issue? 
Thanks a lot.

**Comment by morrownr** [comment]
Hi,

> Is this a known issue?

No. However, that does not mean that it is working. This driver is very heavily used but I haven't had any reports of ad-hoc use and it is not a mode that I test. I can try to help as I have time but right now I have several things I am working on. Let me know if you make any progress.

Regards

**Comment by smydoudou** [comment]
> 

Thank you for your reply. I will continue test or find other solution in my project.
