### ISSUE TITLE
update kernel. Second driver installed.

### ISSUE THREAD

**Issue by LargePrime** [morrownr/8812au-20210629#60]
install driver

sudo dkms status
rtl8812au/5.13.6, 5.18.5-artix1-1, x86_64: installed

update kernel

sudo dkms status
rtl8812au/5.13.6: added
rtl8812au/5.13.6.r119.gedb17ca: added

Please advise.

**Comment by Finoderi** [comment]
Regularly go outside for a walk. Eat more vegetables. Exercise.

**Comment by LargePrime** [comment]
kernel update to 5.18.6-artix1-1
Same thing happened.

**Comment by morrownr** [comment]
Exercise and more vegitables is a good idea but...

dkms seems to not be working on your distro. I have added 2 scripts for those situations.

You can run...

sudo ./remove-driver.sh

download the updated version of the driver and run...

sudo ./install-driver-no-dkms.sh
