### ISSUE TITLE
No handshakes are shown in 5Ghz

### ISSUE THREAD

**Issue by tho-fu** [morrownr/8812au-20210629#70]
Hello all,

my device is working fine with this great driver.

Only one thin is going wrong, the handshakes will not be shown in airodump-ng.
2,4 GHz WPA2 seems to work.
5 GHz not.

I start it with:
`airodump-ng wlan1 --band abg --gpsd`

My Client is under 1m to the Alfa Awus036ach.
No reaction when i reconnect my client to my AP.

Have anyone an idea? :)

Thanks
Thomas

> Raspberry Pi 4B 4GB RAM with Alfa AWUS036ACH - Driver downloaded from git on Sep 18 2022

> uname -mr

`5.15.61-v7l+ armv7l`

> mokutil --sb-state

`EFI variables are not supported on this system`

> lsusb

`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

> rfkill list all

`0: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: phy1: Wireless LAN
	Soft blocked: no
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no`

> dkms status

`rtl8812au, 5.13.6, 5.15.61-v7l+, armv7l: installed`

> iw dev

`phy#1
	Interface wlan1
		ifindex 4
		wdev 0x100000001
		addr 00:c0:ca:b0:8a:0d
		type monitor
		channel 1 (2412 MHz), width: 20 MHz (no HT), center1: 2412 MHz
		txpower 17.00 dBm
phy#0
	Interface wlan0
		ifindex 3
		wdev 0x1
		addr dc:a6:32:17:c9:91
		type managed
		channel 34 (5170 MHz), width: 20 MHz, center1: 5170 MHz
		txpower 31.00 dBm`

> iw reg get

`global
country 00: DFS-UNSET
	(2402 - 2472 @ 40), (6, 20), (N/A)
	(2457 - 2482 @ 20), (6, 20), (N/A), AUTO-BW, PASSIVE-SCAN
	(2474 - 2494 @ 20), (6, 20), (N/A), NO-OFDM, PASSIVE-SCAN
	(5170 - 5250 @ 80), (6, 20), (N/A), AUTO-BW, PASSIVE-SCAN
	(5250 - 5330 @ 80), (6, 20), (0 ms), DFS, AUTO-BW, PASSIVE-SCAN
	(5490 - 5730 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN
	(5735 - 5835 @ 80), (6, 20), (N/A), PASSIVE-SCAN
	(57240 - 63720 @ 2160), (N/A, 0), (N/A)

phy#0
country 99: DFS-UNSET
	(2402 - 2482 @ 40), (6, 20), (N/A)
	(2474 - 2494 @ 20), (6, 20), (N/A)
	(5140 - 5360 @ 160), (6, 20), (N/A)
	(5460 - 5860 @ 160), (6, 20), (N/A)`

**Comment by morrownr** [comment]
Hi @tho-fu 

I must have missed this issue.

> country 00: DFS-UNSET

You should set your country code. There are a few ways to do this including ...

Preferrences > Raspberry Pi Configuration

Is the original problem still there?
