### ISSUE TITLE
unable to compile 6.1.1 kernel

### ISSUE THREAD

**Issue by dardares** [morrownr/8812au-20210629#78]
Hi,
Since the release of 6.1.x kernel, i was unable to install the driver. I've downloaded the latest version as of today (28 Dec 2022)
There is the error i got:
Running install-driver.sh version 20221126
Kernel=6.1.1
Architecture=x86_64
Installing 8812au.conf to: /etc/modprobe.d
The dkms installation routines are in use.
Copying source files to: /usr/src/rtl8812au-5.13.6
Creating symlink /var/lib/dkms/rtl8812au/5.13.6/source -> /usr/src/rtl8812au-5.13.6
The driver was added successfully.
Sign command: /lib/modules/6.1.1/build/scripts/sign-file
Binary /lib/modules/6.1.1/build/scripts/sign-file not found, modules won't be signed

Building module:
Cleaning build area...
'make' -j6 KVER=6.1.1 KSRC=/lib/modules/6.1.1/build........(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.1 (x86_64)
Consult /var/lib/dkms/rtl8812au/5.13.6/build/make.log for more information.
An error occurred. dkms build error = 10
Please report this error.
Please copy all screen output and paste it into the report.
Run the following before reattempting installation.
$ sudo ./remove-driver.sh

If i try to compile it on the Kali 6.0 kernel (not 6.1 or 6.1.1) this working fine without error. As soon i boot to a newer kernel, i was unable to get my adapter working. 

Here is the full log file:
DKMS make.log for rtl8812au-5.13.6 for kernel 6.1.1 (x86_64)
Wed 28 Dec 2022 09:40:44 AM EST
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.1.1/build M=/var/lib/dkms/rtl8812au/5.13.6/build  modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.1'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Debian 12.2.0-9) 12.2.0
  You are using:           gcc (Debian 12.2.0-10) 12.2.0
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_chplan.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/monitor/rtw_radiotap.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/wds/rtw_wds.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_ft.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_wnm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_mbo.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_rm_util.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_roch.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/aes-internal.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/aes-internal-enc.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/aes-gcm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/aes-ccm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/aes-omac1.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/ccmp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/gcmp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/aes-siv.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/aes-ctr.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/sha256-internal.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/sha256.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/sha256-prf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/crypto/rtw_crypto_wrap.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/core/rtw_swcrypto.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/usb_ops_linux.o
/var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.c: In function ‘rtw_ethtool_get_drvinfo’:
/var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.c:2048:19: error: ‘struct net_device’ has no member named ‘ieee80211_ptr’
 2048 |         wdev = dev->ieee80211_ptr;
      |                   ^~
  CC [M]  /var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/ioctl_linux.o
/var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.c: In function ‘rtw_ndev_destructor’:
/var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.c:4493:17: error: ‘struct net_device’ has no member named ‘ieee80211_ptr’
 4493 |         if (ndev->ieee80211_ptr)
      |                 ^~
In file included from /var/lib/dkms/rtl8812au/5.13.6/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.c:17:
/var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.c:4494:37: error: ‘struct net_device’ has no member named ‘ieee80211_ptr’
 4494 |                 rtw_mfree((u8 *)ndev->ieee80211_ptr, sizeof(struct wireless_dev));
      |                                     ^~
/var/lib/dkms/rtl8812au/5.13.6/build/include/osdep_service.h:276:53: note: in definition of macro ‘rtw_mfree’
  276 | #define rtw_mfree(pbuf, sz)             _rtw_mfree((pbuf), (sz))
      |                                                     ^~~~
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/rtl8812au/5.13.6/build/os_dep/linux/os_intfs.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1992: /var/lib/dkms/rtl8812au/5.13.6/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.1'
make: *** [Makefile:2513: modules] Error 2

Thank!

**Comment by morrownr** [comment]
Hi @dardares 

I just tested with kernel 6.1.1, gcc 12.1 on my Xubuntu 22.10 box. Clean compile. 

This is a problem somewhere in the dev environment. As silly as it may sound, try this:

$ sudo update
$ sudo upgrade
$ sudo reboot
$ sudo ./remove-driver.sh
$ sudo ./install-driver.sh
$ sudo reboot

**Comment by dardares** [comment]
Hi,
Thank for the answer. I'm using kali linux 2022.3.
I've just tryied the command you ask me to try. First thing, the sudo apt update command and sudo upgrade command didn't work in kali, so i used: sudo apt-get update and sudo apt-get upgrade
Then i uninstalled the driver whit sudo ./remove-driver.sh
The uninstall script recommend to reboot after uninstall, so i rebooted my computer, then i do sudo ./install-driver.sh. Got the exact same error.
If i boot on the Kali 6.0 Kernel, and do the exact same step, didn't get any error.
Thank

**Comment by morrownr** [comment]
Well, how did you install 6.1.1?

I've been working on some improvements to the scripts that will help catch more issues. I haven't moved those changes into this driver yet so let me take a look at doing that.

**Comment by dardares** [comment]
Hi,
I've installed the kernel using those step:
1. Cloned the kernel into a empty directory
2. Copied the config files for my current kernel to the new kernel config (sudo cp -v /boot/config-$(uname -r) .config
3. Use of the make -j 6 deb-pkg
4. Installed the generated .deb for linux-images, linux-headers, linux-libc
5. Rebooted onto the new kernel then tryied installation

Thank

**Comment by morrownr** [comment]
I basically did the same thing with minor variation...

make -j4
sudo make install

Did you follow installation step 3 for Debian, Kali?

sudo apt install -y linux-headers-$(uname -r) build-essential bc dkms git libelf-dev

Change apt to apt-get if needed.

**Comment by dardares** [comment]
Hi,

I've tryied to uninstall all of the manually compiled kernel, then reinstall it whit your instruction whit make and make install. The make command work well, but the make install command fail. I will need to troubleshoot furthermore why my kernel is not compiling. 

Thank for your help

**Comment by morrownr** [comment]
Hi @dardares 

If the make command is completing, the driver is compiling the driver. It seems the problem is with installation.

Do you already have a driver of the same name installed? How about we try:

$ lsmod

post the results

$ dkms status

post the results

$ make clean
$ make
$ sudo make install

post the results of sudo make install

Nick

**Comment by dardares** [comment]
I'm closing the issue. Since i was unable to compile the newer kernel after uninstall it for testing purposes, and since you confirmed me you was able to install it on newer kernel whit another distros, i can now say the issue is not whit the driver. It located somewhere else in my kernel configuration and i will need to troubleshoot it furthermore at my side. Thank for your time.
