### ISSUE TITLE
ID 2001: 3314 D-Link Corp.

### ISSUE THREAD

**Issue by ortegahernandes** [morrownr/8812au-20210629#8]
The model device (DWA-171-A1) is not working.

Could you include?

ID 2001: 3314 D-Link Corp. DWA-171 AC600 DB Wireless Adapter (rev.A1) [Realtek RTL8811AU]

https://www.dlink.com.br/produto/adaptador-wireless-usb-ac600-dwa-171/

**Comment by morrownr** [comment]
Hi @ortegahernandes 

> ID 2001: 3314 D-Link Corp. DWA-171 AC600 DB Wireless Adapter (rev.A1) [Realtek RTL8811AU]

This driver is not for the 8811au. It is for the 8812au. Please remove this driver and install the driver in the following repo:

https://github.com/morrownr/8821au-20210708

Regards

**Comment by ortegahernandes** [comment]
thank you so much
