### ISSUE TITLE
Deauth 5GHZ NOT WORK

### ISSUE THREAD

**Issue by vincenzogianfelice** [morrownr/8812au-20210629#81]
OS: **Debian 11** (linux-5.10)

Hi. When I try to deauth on the 5GHZ network (**AWUS036AC**), aireplay-ng works fine but no one is deauthenticated. How is it possible?
Has anyone solved? This story has been going on for years now!

I have tried set more country (**US**,**BO**,**ID**) but not wor:

```
global
country ID: DFS-JP
        (2400 - 2483 @ 40), (N/A, 26), (N/A), NO-OUTDOOR
        (5150 - 5350 @ 80), (N/A, 23), (N/A), NO-OUTDOOR
        (5725 - 5825 @ 80), (N/A, 23), (N/A), NO-OUTDOOR
```

**Comment by morrownr** [comment]
Hi @vincenzogianfelice 

I need you to provide the exact steps you are using for the deauth so that I can try to duplicate the problem.

Nick
