### ISSUE TITLE
Raspberry PI kernel header problem

### ISSUE THREAD

**Issue by ELias-Tre** [morrownr/8812au-20210629#90]
When attempting to run install-driver.sh after exact same installation as recommended with reboot and stuff it tells me that my kernel headers aren't properly installed. I've tried this like twice and can't figure out what drivers are needed. Please help me

**Comment by morrownr** [comment]
Take a look:

https://github.com/morrownr/88x2bu-20210702/issues/136

**Comment by ELias-Tre** [comment]
For some reason it works now. Maybe kernel headers were updated

**Comment by morrownr** [comment]
The RasPiOS engineers may have fixed it and it flowed into your system during an update.
